services:
  llmstudio:
    image: h2oairelease/h2oai-llmstudio-app:latest
    container_name: llmstudio
    runtime: nvidia
    restart: always
    ports:
      - "10101:10101"
    volumes:
      - ~/llmstudio_mnt:/mount
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - WAVE_ALLOW_INSECURE_HOST=true
      - WAVE_PASSWORD=admin
    shm_size: 64g
    init: true
    networks:
      - llm-net

  # llmnginx:
  #   image: nginx:alpine
  #   container_name: llmstudio-nginx
  #   restart: always
  #   ports:
  #     - "10101:80"
  #   volumes:
  #     - ./nginx/llmstudio.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
  #   depends_on:
  #     - llmstudio
  #   networks:
  #     - llm-net

networks:
  llm-net:
    driver: bridge