services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ollama_blobs:/root/.ollama/models/blobs
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  rag-web-ui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: rag-web-ui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

      - ENABLE_RAG=true
      - RAG_EMBEDDING_ENGINE=ollama
      - RAG_EMBEDDING_MODEL=nomic-embed-text
      - RAG_EMBEDDING_DIM=768
      - VECTOR_DB=qdrant
      - QDRANT_URI=http://qdrant:6333
      - WEBUI_NAME=My RAG WebUI
      - WEBUI_LANGUAGE=ja

  post-train-ui:
    build: ./post-train-ui
    container_name: post-train-ui
    ports:
      - "8501:8501"
    volumes:
      - ollama_blobs:/models/blobs
      - ./post-train-ui:/app
      - ./llama.cpp:/llama.cpp
      - /home/ubuntu/llmstudio_mnt:/h2o-output:ro
    depends_on:
      - ollama
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - rag-web-ui
      - post-train-ui
    restart: unless-stopped

volumes:
  ollama_data:
  qdrant_data:
  ollama_blobs: